//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MantenimientoPY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ciudadano
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ciudadano()
        {
            this.Denuncias = new HashSet<Denuncia>();
            this.ContactosEmergencias = new HashSet<ContactosEmergencia>();
        }
    
        public int idCiudadano { get; set; }
        public string nombreCiudadano { get; set; }
        public string apellidoPatCiudadano { get; set; }
        public string apellidoMatCiudadano { get; set; }
        public string direccionCiudadano { get; set; }
        public string passwordCiudadano { get; set; }
        public string correoCiudadano { get; set; }
        public Nullable<int> estadoCiudadano { get; set; }
        public Nullable<int> numReportesFalsosCiudadano { get; set; }
        public Nullable<int> telefonoCiudadano { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Denuncia> Denuncias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContactosEmergencia> ContactosEmergencias { get; set; }
    }
}
