//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MantenimientoPY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactosEmergencia
    {
        public int idContactoEmergencia { get; set; }
        public int idCiudadano { get; set; }
        public int numContactoEmergencia { get; set; }
        public string nombreContactoEmergencia { get; set; }
    
        public virtual Ciudadano Ciudadano { get; set; }
    }
}
