//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MantenimientoPY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Denuncia
    {
        public int idDenuncia { get; set; }
        public int idCiudadano { get; set; }
        public Nullable<int> idPolicia { get; set; }
        public int idTipoDenuncia { get; set; }
        public int idTipoDelito { get; set; }
        public Nullable<int> idEstadoDenuncia { get; set; }
        public decimal latitudDenuncia { get; set; }
        public decimal longitudDenuncia { get; set; }
        public string descripcionDenuncia { get; set; }
        public string afectadoDenuncia { get; set; }
    
        public virtual Ciudadano Ciudadano { get; set; }
        public virtual TipoDenuncia TipoDenuncia { get; set; }
        public virtual TipoDelito TipoDelito { get; set; }
        public virtual EstadoDenuncia EstadoDenuncia { get; set; }
        public virtual Policia Policia { get; set; }
    }
}
