//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MantenimientoPY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Policia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Policia()
        {
            this.Denuncias = new HashSet<Denuncia>();
            
        }
    
        public int idPolicia { get; set; }
        public int idTipoUsuario { get; set; }
        public Nullable<int> identificacionPolicia { get; set; }
        public string nombrePolicia { get; set; }
        public string apellidoPaternoPolicia { get; set; }
        public string apellidoMaternoPolicia { get; set; }
        public string direccionPolicia { get; set; }
        public Nullable<int> telefonoPolicia { get; set; }
        public string correoPolicia { get; set; }
        public string passwordPolicia { get; set; }
        public Nullable<int> estadoPolicia { get; set; }
        string _nombreCompleto;
        public string nomCompleto
        {
            get
            {
                _nombreCompleto = nombrePolicia + " " + apellidoPaternoPolicia + " " + apellidoMaternoPolicia;
                return this._nombreCompleto;
            }
            set
            {
                _nombreCompleto = nombrePolicia + " " + apellidoPaternoPolicia + " " + apellidoMaternoPolicia;
                this._nombreCompleto = value;
            }

        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Denuncia> Denuncias { get; set; }
        public virtual TipoUsuario TipoUsuario { get; set; }
    }
}
