//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MantenimientoPY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoDelito
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TipoDelito()
        {
            this.Denuncias = new HashSet<Denuncia>();
        }
    
        public int idTipoDelito { get; set; }
        public string nombreTipoDelito { get; set; }
        public string descripcionTipoDelito { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Denuncia> Denuncias { get; set; }
    }
}
